database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "good-user"
  password: "good-password"
  dbname: "reward_management_system_1"
  sslmode: "disable"
restServerConfig: 
  port: 8080
schedulerConfig: 
  schedulerRunnerTimeInMin: 2
  expireTimeYear: 1
  expireTimeMonth: 0
  expireTimeDay: 0
jwtSecret: "abcdefghijklmnopqrstuvwxyz"
accessTokeTime: 5
refreshTokenTime: 1